name: Deploy to ECS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: todo-app
  ECS_CLUSTER: test1
  ECS_SERVICE: todo-service-sz9bxsxk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::418272785046:role/github-web-identity
          aws-region: ap-northeast-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # üî• latest ÌÉúÍ∑∏Î°ú ÎπåÎìú
      - name: Build Docker image
        run: docker build -t todo-app:latest .

      # üî• ECR latest ÌÉúÍ∑∏Î°ú ÎçÆÏñ¥Ïì∞Í∏∞
      - name: Tag image
        run: |
          docker tag todo-app:latest \
          418272785046.dkr.ecr.ap-northeast-2.amazonaws.com/todo-app:latest

      - name: Push image
        run: |
          docker push \
          418272785046.dkr.ecr.ap-northeast-2.amazonaws.com/todo-app:latest

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster test1 \
            --service todo-service-sz9bxsxk \
            --force-new-deployment
